---
sudo: required

env:
  - distribution: ubuntu
    version: bionic
  #- distribution: centos
  #  version: 8
  #- distribution: fedora
  #  version: 31
  #- distribution: debian
  #  version: buster

services:
  - docker

before_install:
  - 'sudo ./testing/1_create.sh ${distribution} ${version}'

script:
  - container_id=$(mktemp)
  - 'sudo ./testing/2_run.sh ${distribution} ${version} ${container_id}'
  - 'sudo docker exec "$(cat ${container_id})" /etc/ansible/roles/git-tools/testing/4_test.sh --idempotence'
  - 'sudo ./testing/5_remove.sh ${container_id}'
