---
- name: "ensure local folder exists: '{{ git_user_home }}/.local/bin'"
  file:
    path: "{{ git_user_home }}/.local/bin"
    state: directory

- name: "ensure local folder exists: '{{ git_user_home }}/.local/share'"
  file:
    path: "{{ git_user_home }}/.local/share"
    state: directory
