---
- import_tasks: tasks/centos_prerequisites.yml
  when: ansible_distribution == "CentOS"

- name: install git tools
  become: yes
  package:
    name:
      - git
      - git-gui
      - gitk

- name: set user global push strategy to simple
  git_config:
    scope: global
    name: "push.default"
    value: "simple"

- name: set user global pull strategy to always use --rebase
  git_config:
    scope: global
    name: "pull.rebase"
    value: "true"

- import_tasks: tasks/user.yml
  when: git_user_name != ""

- import_tasks: tasks/aliases.yml
  when: git_aliases

- import_tasks: tasks/archivestotext.yml
  when: git_archivestotext
- import_tasks: tasks/docxtotext.yml
  when: git_docxtotext
- import_tasks: tasks/pdftotext.yml
  when: git_pdftotext
- import_tasks: tasks/xlsxtotext.yml
  when: git_xlsxtotext

- import_tasks: tasks/rerere.yml
  when: git_rerere

- import_tasks: tasks/editor_nano.yml
  when: git_editor_nano

- import_tasks: tasks/prompt.yml
  when: git_prompt
