---
- name: enable rerere globaly for user
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {name: 'rerere.enabled', value: 'true'}
    - {name: 'rerere.autoupdate', value: 'true'}
