---
- hosts: localhost

  pre_tasks:
    - name: Update package manager repositories
      become: yes
      package: update_cache=yes
      changed_when: false

  roles:
    - { role: git-tools,
        #git_user_name: "Christian Lang",
        #git_user_email: "lang.chr86@gmail.com",
        git_rerere: on,
        git_editor_nano: on,
        git_prompt: on
    }
