name: ansible_run

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-bionic
          - ubuntu-focal
          - centos-7
          - fedora-31
          - debian-buster

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: System information
        run: |
          uname -a
          lsb_release -a
          sudo docker --version

      - name: Prepare container, run, test and cleanup
        run: |
          sudo ./testing/1_create.sh ${{matrix.distro}}
          export container_id=$(mktemp)
          sudo ./testing/2_run.sh ${{matrix.distro}} ${container_id}
          sudo docker exec "$(cat ${container_id})" /etc/ansible/roles/git-tools/testing/4_test.sh --idempotence
          sudo ./testing/5_remove.sh ${container_id}
